version: '3'

services:
    app:
        image: streamlit-docker
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            - PORT=8000
        ports:
            - 8000:8000
        volumes:
            - ./app:/usr/app/src/