version: '3'

services:
    app:
        image: el_barto
        build:
            dockerfile: ./Dockerfile
            context: .
        environment:
            - PORT=8080
        ports:
            - 8080:8080
        volumes:
            - ./app:/usr/app/src/